### ISSUE TITLE
Nothing to unfollow

### ISSUE THREAD

**Issue by david-kariuki** [Correia-jpv/github-follow-bot#13]
Hello there, I sam still getting the `Nothing to unfollow` message when trying to unfollow

**Comment by Correia-jpv** [comment]
Please, further describe context. What command are you using?

**Comment by david-kariuki** [comment]
All the unfollow commands are not working

**Comment by Correia-jpv** [comment]
Would you be able to share logs?

**Comment by david-kariuki** [comment]
This is the error I'm getting now


     Traceback (most recent call last):
        File "/home/user/bash/github-follow-bot-master/bot_unfollow.py", line 38, in <module>
        bot = GithubAPIBot(
        ^^^^^^^^^^^^^
        File "/home/user/bash/github-follow-bot-master/GithubAPIBot.py", line 68, in __init__
        self.getFollowings()
        File "/home/user/bash/github-follow-bot-master/GithubAPIBot.py", line 226, in getFollowings
        self.followings.extend(self.getUsers(url=f"https://api.github.com/users/{username}/following"))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/home/user/bash/github-follow-bot-master/GithubAPIBot.py", line 192, in getUsers
        and not (user["login"] in self.followings)
        ~~~~^^^^^^^^^
        TypeError: string indices must be integers, not 'str'

**Comment by Correia-jpv** [comment]
Ok, provide more context. What exactly is the command you are running? Have you changed any code at all?

**Comment by david-kariuki** [comment]
No, I have not changed the code. I've cloned this again and ran it on opera using python3

    python3 bot_unfollow.py -a
